export const SET_ADMIN_API_ACCESS_TOKEN = "SET_ADMIN_API_ACCESS_TOKEN";
export const SET_ADMIN_INFO = "SET_ADMIN_INFO";
export const RESET_ADMIN_INFO = "RESET_ADMIN_INFO";

export const APP_TOGGLE_SIDER_COLLAPSED = "APP_TOGGLE_SIDER_COLLAPSED";
export const APP_TOGGLE_SETTING_PANEL = "APP_TOGGLE_SETTING_PANEL";
export const APP_SETTING_CHANGE = "APP_SETTING_CHANGE";

export const ADD_TAG = "ADD_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const EMPTY_TAGS = "EMPTY_TAGS";
export const CLOSE_OTHER_TAGS = "CLOSE_OTHER_TAGS";
